### ISSUE TITLE
Problem with two-factor authentication on GitHub. After a month it stopped working

### ISSUE THREAD

**Issue by Noncle** [uyriq/mytotp_as_bashfuncs#1]
Problem with GitHub 2fa. I installed according to the readme, i.e. I received from GitHub the installation key (the phrase that represents the qr code) I created a record using mytotpadd and everything worked fine, i.e. using mytotp <record> I get the six digit code and GitHub recognizes it! Now closer to the problem. For some unknown reason about a month after initial use, the generated codes stopped being valid and repeatedly fail to install a new otp record! This problem is critical to use!

**Comment by uyriq** [comment]
latest commit 33cf200 works with upgraded bash, not with default
